FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip \
    openssh-client sshpass \
    git curl ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Install ansible
RUN pip3 install --no-cache-dir ansible==9.* passlib

WORKDIR /work
